services:
  - type: web
    name: worked-note
    env: python
    buildCommand: "pip install -r requirements.txt && python server/manage.py collectstatic --no-input && python server/manage.py migrate"
    startCommand: "gunicorn --chdir server config.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - fromDatabase:
          name: worked-note-db
          property: connectionString

databases:
  - name: worked-note-db
    plan: free
    databaseName: worked_note
    user: admin
