services:
  - type: web
    name: worked-note
    env: python
    buildCommand: "pip install -r requirements.txt && python server/manage.py collectstatic --no-input --clear && python server/manage.py migrate"
    startCommand: "gunicorn --chdir server config.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
