# Generated by Django 4.2 on 2026-04-17 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('color', models.IntegerField(choices=[(0, '기본'), (1, '업무'), (2, '개인'), (3, '중요'), (4, '아이디어')], default=0, verbose_name='카테고리')),
                ('pinned', models.BooleanField(default=False, verbose_name='고정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모',
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호')),
                ('kakao_id', models.CharField(blank=True, default='', max_length=50, verbose_name='카카오톡 ID')),
                ('group', models.CharField(choices=[('일반', '일반'), ('팀원', '팀원'), ('거래처', '거래처'), ('외부', '외부'), ('VIP', 'VIP')], default='일반', max_length=20, verbose_name='그룹')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '연락처',
                'verbose_name_plural': '연락처',
                'ordering': ['name'],
            },
        ),
    ]
