# Generated by Django 4.2 on 2026-04-17 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='공유 여부'),
        ),
        migrations.AddField(
            model_name='memo',
            name='share_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='공유 토큰'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField(verbose_name='알림 일시')),
                ('channel', models.CharField(default='email', max_length=20, verbose_name='알림 채널')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='반복 여부')),
                ('is_sent', models.BooleanField(default=False, verbose_name='발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='memos.memo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림 예약',
                'verbose_name_plural': '알림 예약',
            },
        ),
    ]
