# Generated by Django 4.2 on 2026-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_memo_is_shared_memo_share_token_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.CharField(choices=[('일반', '일반'), ('팀원', '팀원'), ('거래처', '거래처'), ('외부', '외부'), ('VIP', 'VIP'), ('회사', '회사'), ('개인', '개인')], default='일반', max_length=20, verbose_name='그룹'),
        ),
    ]
