# Generated by Django 4.2 on 2026-04-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0005_memo_is_public_memo_share_slug_memocomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
