# Generated by Django 4.2 on 2026-04-17 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', '이메일'), ('sms', '문자'), ('kakao', '카카오톡')], max_length=10, verbose_name='채널')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('status', models.CharField(choices=[('pending', '대기'), ('sent', '발송완료'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='에러 메시지')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일')),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='memos.memo')),
                ('recipients', models.ManyToManyField(related_name='received_messages', to='memos.contact', verbose_name='수신자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '발송 기록',
                'verbose_name_plural': '발송 기록',
                'ordering': ['-sent_at'],
            },
        ),
    ]
